version: '3.5'

services:

  mysql-development:
    image: mysql:8.0.17
    container_name: ppb-mysql
    hostname: ppb-mysql
    environment:
      MYSQL_ROOT_PASSWORD: qwertyui
      MYSQL_DATABASE: horoscope
    ports:
      - "3308:3306"
      
  horoscope:
    build: ppb-product-horoscope
    ports:
      - "8081:8080"
    environment:
      WAIT_HOSTS: ppb-mysql:3306
    command: sh -c "/ppb-product-horoscope/wait && java -jar /ppb-product-horoscope/app.jar"
      
networks:
  default:
    external:
        name: ppb
