version: '3.5'

services:

  mysql-development:
    image: mysql:8.0.17
    container_name: ppb-mysql
    hostname: ppb-mysql
    environment:
      MYSQL_ROOT_PASSWORD: qwertyui
    ports:
      - "3308:3306"
    volumes:
          - ./src/main/resources/db:/docker-entrypoint-initdb.d
          - ../mysql-data:/var/lib/mysql

  billingcore:
    build: ppb-product-billingcore
    ports:
      - "8080:8080"
    container_name: ppb-product-billingcore
    hostname: ppb-product-billingcore
    environment:
      WAIT_HOSTS: ppb-mysql:3306
    command: sh -c "/ppb-product-billingcore/wait && java -jar /ppb-product-billingcore/app.jar"
      
  horoscope:
    build: ppb-product-horoscope
    ports:
      - "8081:8080"
    container_name: ppb-product-horoscope
    hostname: ppb-product-horoscope
    environment:
      WAIT_HOSTS: ppb-mysql:3306
    command: sh -c "/ppb-product-horoscope/wait && java -jar /ppb-product-horoscope/app.jar"
      
networks:
  default:
    external:
        name: ppb
